import Head from 'next/head';
import Link from 'next/link';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";  
import Image from "next/image";
import deved from '../public/varunfly.jpeg';
import brewery from '../public/breweries.png';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Varun Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className='min-h-screen'>
            <nav className="py-10 mb-12 flex flex-wrap justify-between mx-auto max-w-3xl">
              <h1 className="text-xl font-burtons">Varun Manjunath</h1>
              <Link href="/#about" className="px-4 py-2 rounded-md ml-8 transition ease-in-out bg-green-500 duration-100 text-white hover:scale-110 hover:shadow-2xl shadow-sm cursor-pointer ">About me</Link>
              <Link href="/#projects" className="px-4 py-2 rounded-md ml-8 transition ease-in-out bg-green-500 duration-100 text-white hover:scale-110 hover:shadow-2xl shadow-sm cursor-pointer">Projects</Link>
              <Link href="/varun-resume.pdf" className="px-4 py-2 rounded-md ml-8 transition ease-in-out bg-green-500 duration-100 text-white hover:scale-110 hover:shadow-2xl shadow-sm cursor-pointer">Resume</Link>
            </nav>
            <div id="about">
              <div className="text-center py-10 mb-12 justify-between mx-auto max-w-3xl">
                <h3 className="text-5xl"> Introduction </h3>
                <br/>
                <p className="text-2xl text-gray-600">
                  I am Varun Manjunath a 2nd year Computer Science Master&apos;s Student at 
                  The University of Colorado,Boulder.My areas of interest include Machine Learning as well as Full Stack Web Development.
                  In addition to that I enjoy playing Table Tennis and Badminton.
                </p>
              </div>
              <div className="text-3xl flex justify-center gap-10 py-3 text-gray-600">
                <div>
                  <div>Linkedin</div>
                  <div className="ml-9 relative"> <a href="https://www.linkedin.com/in/varun-manjunath1/"><AiFillLinkedin/></a></div>
                </div>
                <div>
                  <div>Github</div>
                  <div className="ml-6 relative"><a href="https://github.com/varunmanju"><AiFillGithub/></a></div>
                </div>
              </div>
              <div className="relative mx-auto transition ease-in-out hover:scale-110 my-8 flex justify-center">
                <Image src={deved} width={600} alt="Varun" />
              </div>
              <div className="text-center py-10 mb-12 justify-between mx-auto max-w-3xl">
                <h3 className="text-5xl">Skills</h3>
                <br/>
                <div className="grid grid-cols-3 gap-4 grid-wrap">
                  <div className="px-4 py-2 rounded-md ml-8 border-2 border-indigo-600 cursor-pointer ">Kubernetes</div>
                  <div className="px-4 py-2 rounded-md ml-8 border-2 border-indigo-600 cursor-pointer ">Docker</div>
                  <div className="px-4 py-2 rounded-md ml-8 border-2 border-indigo-600 cursor-pointer ">Ansible</div>
                  <div className="px-4 py-2 rounded-md ml-8 border-2 border-indigo-600 cursor-pointer ">Machine Learning</div>
                  <div className="px-4 py-2 rounded-md ml-8 border-2 border-indigo-600 cursor-pointer ">Deep Learning</div>
                  <div className="px-4 py-2 rounded-md ml-8 border-2 border-indigo-600 cursor-pointer ">React</div>
                  <div className="px-4 py-2 rounded-md ml-8 border-2 border-indigo-600 cursor-pointer ">Flask</div>
                  <div className="px-4 py-2 rounded-md ml-8 border-2 border-indigo-600 cursor-pointer ">Python</div>
                  <div className="px-4 py-2 rounded-md ml-8 border-2 border-indigo-600 cursor-pointer ">Java</div>
                </div>
              </div>
            </div>
          
          <div id="projects" className="text-center py-10 mb-12 justify-between mx-auto max-w-3xl">
            <h3 className="text-5xl">Projects</h3>
            <div className="grid grid-cols-2 grid-wrap my-8 relative gap-14">
              <div className="flex flex-col justify-between max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                <div>
                  <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Brewery React App</h5>
                  <p className="font-normal text-gray-700 dark:text-gray-400">A brewery react app that implements search functionality. The user can search the breweries based on the location, address, state,city and number</p>
                </div>
                <Link href="https://github.com/varunmanju/brewery-react-app" className="px-4 py-2 rounded-md transition ease-in-out bg-indigo-600 duration-100 text-white hover:scale-110 hover:shadow-2xl shadow-sm cursor-pointer">Project</Link>
              </div>
              <div className="relative mx-auto max-w-sm transition ease-in-out hover:scale-110">
                <Image className="rounded-lg" src={brewery} alt={"project screenshot"} />
              </div>
           </div>
            
          </div>
        </section>
      </main>
    </div>
  );
}
